apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "vcluster.csi.secret.store"
spec:
  type: Mutating
  operations: ["CREATE", "UPDATE"]
  resources: ["pods", "deployments"]
  scope: "*"
  objectSelector:
    matchExpressions:
    - key: "vcluster.loft.sh/managed-by"
      operator: Exists
  matchPolicy: "Equivalent"
  apiGroups: ["*"]
  apiVersions: ["*"]
  # Optional javascript here
  javascript: |
    request.object.spec.volumes?.forEach((volume, index) => {
      let driver = volume["csi"]?.driver
      if (driver == "secrets-store.csi.k8s.io") {
        let hostNs = request.object.metadata.namespace
        let vclusterNs = request.object.metadata.annotations['vcluster.loft.sh/namespace']
        let secretProviderClass = volume["csi"]["volumeAttributes"]["secretProviderClass"]
        request.object.spec.volumes[index]['csi']["volumeAttributes"]["secretProviderClass"] =
          `${secretProviderClass}-x-${vclusterNs}-x-${hostNs}`
      }
    })
    // tell jspolicy to calc the patch and exit
    mutate(request.object);